### ISSUE TITLE
Knight, Slayer, Scout, Hunter can choose features from their corresponding subclass

### ISSUE THREAD

**Issue by thoth-process** [CBLoader/CBParts#104] opened 2022-01-25 01:54 UTC
Knights can choose Slayer Stances, and vice versa, and Hunters can choose Scout Aspects, and vice versa. Despite it making a ton of sense, it is not RAW since these are unleveled powers, so the Categories for the corresponding subclasses should be removed.

**Comment by silasary** [comment] 2022-01-25 04:50
I'll try to find the (8 year old) twitter conversation where I got dev confirmation, but this is actually the intended behavior. 

For a long time, Vecna supported it and CBLoader didn't, but the parts were intentionally changed to this behaviour in 2017.

**Comment by silasary** [comment] 2022-01-25 04:51
If a GM wants to disallow it, they're welcome to. and CBLoader does visually distinguish the off-class stances.  But this is a WONTFIX

**Closed by silasary** 2022-01-25 04:50 UTC
